version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - "$PWD/db/:/docker-entrypoint-initdb.d/"
  coffee_cabal:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - '8000:8000'
  load_data:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - '8000:8000'
    entrypoint: [ python ]
    command: "-m app.loader.main"
volumes:
  db:
    driver: local